version: '3'
services:
  php:
    build: .
    ports:
      - 80:80
    volumes:
      - ../geniesys:/var/www/geniesys

  phpmyadmin:
    image: phpmyadmin
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      PMA_ARBITRARY: 1
    ports:
      - 8080:80

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
